document.writeln("<div id=\"new\" class=\"newHeader\">");
document.writeln("    <div class=\"topsearch\">因为相信所以看见");
document.writeln("        <!--<img src=\"img/searchNew.png\"alt=\"\"onclick=\"wapHref(\'http://wap.10010.com/mobileService/search.htm\')\">-->");
document.writeln("    </div>");
document.writeln("    <!--<marquee behavior=\"\"scrolldelay=\"100\"scrollamount=\"1\"direction=\"left\"bgcolor=\"#CCFF66\"width=\"\"height=\"20rem\"><font size=\"2\"color=\"#000\">🎤最新消息：<a href=\"#\"target=\"_blank\"style=\"color:CC6600\">新一轮竞合</a></br></font></marquee>-->");
document.writeln("</div>");
document.writeln("<div class=\"zt_body\">");
document.writeln("    <div class=\"gapTitle\" style=\"background-color:#f0f0f0;height:.2rem;\"></div>");
document.writeln("    <div class=\"zcl\" id=\"tab_li_div\">");
document.writeln("        <ul>");
document.writeln("            <li class=\"lb_li1 oper bj\" data-oper=\"query\" data-index=\"1\">");
document.writeln("                <p>查询</p>");
document.writeln("            </li>");
document.writeln("            <li class=\"lb_li2 oper\" data-oper=\"pay\" data-index=\"2\">");
document.writeln("                <p>手厅</p>");
document.writeln("            </li>");
document.writeln("            <li class=\"lb_li3 oper\" data-oper=\"custom\" data-index=\"3\">");
document.writeln("                <p>话费积分</p>");
document.writeln("            </li>");
document.writeln("            <li class=\"lb_li4 oper\" data-oper=\"custom\" data-index=\"4\">");
document.writeln("                <p>热门活动</p>");
document.writeln("            </li>");
document.writeln("            <li class=\"lb_li5 oper\" data-oper=\"spread\" data-index=\"5\">");
document.writeln("                <p>地区活动</p>");
document.writeln("            </li>");
document.writeln("            <li class=\"lb_li6 oper\" data-oper=\"spread\" data-index=\"6\">");
document.writeln("                <p>湖南专区</p>");
document.writeln("            </li>");
document.writeln("            <li></li>");
document.writeln("            <li></li>");
document.writeln("            <li></li>");
document.writeln("            <li></li>");
document.writeln("        </ul>");
document.writeln("    </div>");
document.writeln("</div>");
document.writeln("<div class=\"t1 div_nav\">");
document.writeln("    <div class=\"t1_1\">");
document.writeln("        <ul>");
document.writeln("            <!--<div class=\"top1\"><a href=\"http://91haoka.cn/webapp/merchant/templet1.html?share_id=386983&id=2493347\"><img width=\"290rem\"height=\"100rem\"src=\"img/top_1.jpg\"></a></div>-->");
document.writeln("            <p style=\"text-align: center;\"><a id=\"obj1\"><img id=\"obj\" src=\"img/bg01.jpg\" width=\"290rem\" height=\"130rem\" border=\"0\" /></a></p>");
document.writeln("            <li name=\"\" onclick=\"window.location.href=\'https://wap.10010.com/mobileService/clickCountLogRecord/pageClickCount.htm?flag=new&amp;urlApp=xxx&amp;urlName=xxx&amp;application=113000010&amp;title=%e6%88%91%e5%b7%b2%e8%ae%a2%e8%b4%ad&amp;openUrl=https%3a%2f%2fm.client.10010.com%2fmobileService%2foperationservice%2fqueryOrderRelationshipTwo.htm\'\"><img src=\"img/20161026170548.png\" onerror=\"javascript:this.src=\'https://img.client.10010.com/mobileService/view/client/wap/images/default_logo.png\';\" class=\"tu1\">");
document.writeln("                <p>我已订购(旧)</p>");
document.writeln("            </li>");
document.writeln("            <li name=\"\" onclick=\"window.location.href=\'https://wap.10010.com/mobileService/clickCountLogRecord/pageClickCount.htm?flag=new&amp;urlApp=xxx&amp;urlName=xxx&amp;application=113000010&amp;title=%e4%bd%99%e9%87%8f%e6%9f%a5%e8%af%a2&amp;openUrl=https%3a%2f%2fm.client.10010.com%2fmobileService%2foperationservice%2fqueryWoComboSpare.htm\'\"><img src=\"img/20161026170637.png\" onerror=\"javascript:this.src=\'https://img.client.10010.com/mobileService/view/client/wap/images/default_logo.png\';\" class=\"tu1\">");
document.writeln("                <p>余量查询(旧)</p>");
document.writeln("            </li>");
document.writeln("            <li name=\"\" onclick=\"window.location.href=\'https://wap.10010.com/mobileService/clickCountLogRecord/pageClickCount.htm?flag=new&urlApp=xxx&urlName=xxx&application=113000010&title=%e4%b8%9a%e5%8a%a1%e5%8a%9e%e7%90%86%e8%ae%b0%e5%bd%95&openUrl=https%3a%2f%2fm.client.10010.com%2fmobileService%2foperationservice%2fqueryHistoryBusinessBL.htm\'\"><img src=\"img/20161026171543.png\" onerror=\"javascript:this.src=\'https://img.client.10010.com/mobileService/view/client/wap/images/default_logo.png\';\" class=\"tu1\">");
document.writeln("                <p>业务办理记录</p>");
document.writeln("            </li>");
document.writeln("            <li name=\"\" onclick=\"window.location.href=\'https://wap.10010.com/mobileService/clickCountLogRecord/pageClickCount.htm?flag=new&urlApp=xxx&urlName=xxx&application=113000010&title=%e6%88%91%e5%b7%b2%e8%ae%a2%e8%b4%ad&openUrl=https://img.client.10010.com/liuliangbaoliebiaov3/index.html\'\"><img src=\"img/20161026171253.png\" onerror=\"javascript:this.src=\'https://img.client.10010.com/mobileService/view/client/wap/images/default_logo.png\';\" class=\"tu1\">");
document.writeln("                <p>流量专区(旧)</p>");
document.writeln("            </li>");
document.writeln("            <li name=\"https://u.10010.cn/uAaqk\" onclick=\"window.location.href=\'https://img.client.10010.com/shengyuhuafei/index.html\'\"><img src=\"img/20161026173300.png\" onerror=\"javascript:this.src=\'https://img.client.10010.com/mobileService/view/client/wap/images/default_logo.png\';\" class=\"tu1\">");
document.writeln("                <p>剩余话费(旧)</p>");
document.writeln("            </li>");
document.writeln("            <li name=\"\" onclick=\"window.location.href=\'https://wap.10010.com/mobileService/clickCountLogRecord/pageClickCount.htm?flag=new&urlApp=xxx&urlName=xxx&application=113000010&title=%e4%bd%99%e9%87%8f%e6%9f%a5%e8%af%a2&openUrl=https://img.client.10010.com/shiyongliangfenxi/index.html\'\"><img src=\"img/20161026174033.png\" onerror=\"javascript:this.src=\'https://img.client.10010.com/mobileService/view/client/wap/images/default_logo.png\';\" class=\"tu1\">");
document.writeln("                <p>使用量分析</p>");
document.writeln("            </li>");
document.writeln("            <li name=\"\" onclick=\"window.location.href=\'https://img.client.10010.com/dwguide/index.html?title=%E8%AF%B7%E7%A8%8D%E5%90%8E&sharerMobile=&openUrl=https%3a%2f%2fimg.client.10010.com%2fwoyidinggou%2findex.html\'\"><img src=\"img/20161026170548.png\" onerror=\"javascript:this.src=\'https://img.client.10010.com/mobileService/view/client/wap/images/default_logo.png\';\" class=\"tu1\">");
document.writeln("                <p>我已订购</p>");
document.writeln("            </li>");
document.writeln("            <li name=\"https://u.10010.cn/qA5AW\" onclick=\"window.location.href=\'https://epay.10010.com/upp/obppWebroot/html/arrearsSelect.html\'\"><img src=\"img/20161026170637.png\" onerror=\"javascript:this.src=\'https://img.client.10010.com/mobileService/view/client/wap/images/default_logo.png\';\" class=\"tu1\">");
document.writeln("                <p>欠费查询</p>");
document.writeln("            </li>");
document.writeln("            <li name=\"\" onclick=\"window.location.href=\'https://img.client.10010.com/dwguide/index.html?title=%E8%AF%B7%E7%A8%8D%E5%90%8E&sharerMobile=&openUrl=https%3a%2f%2fimg.client.10010.com%2fyewubanlijilu%2findex.html\'\"><img src=\"img/20161026171543.png\" onerror=\"javascript:this.src=\'https://img.client.10010.com/mobileService/view/client/wap/images/default_logo.png\';\" class=\"tu1\">");
document.writeln("                <p>业务办理记录</p>");
document.writeln("            </li>");
document.writeln("            <li name=\"\" onclick=\"window.location.href=\'https://wap.10010.com/mobileService/clickCountLogRecord/pageClickCount.htm?flag=new&urlApp=xxx&urlName=xxx&application=113000010&title=%E6%B5%81%E9%87%8F%E5%8C%85&openUrl=https://m.client.10010.com/mobileService/operationservice/queryOrderRelationship.htm&title=%E4%BD%99%E9%87%8F%E6%9F%A5%E8%AF%A2&openUrl=https://wap.10010.com/mobileService/clickCountLogRecord/pageClickCount.htm?flag=new&urlApp=xxx&urlName=xxx&application=113000010&title=%E6%9F%A5%E8%AF%A2&openUrl=https://m.client.10010.com/mobileService/operationservice/queryOrderRelationship.htm&type=6&list_name=%E6%9C%AA%E5%91%BD%E5%90%8D\'\"><img src=\"img/20161026175256.png\" onerror=\"javascript:this.src=\'https://img.client.10010.com/mobileService/view/client/wap/images/default_logo.png\';\" class=\"tu1\">");
document.writeln("                <p>我的流量包</p>");
document.writeln("            </li>");
document.writeln("            <li name=\"\" onclick=\"window.location.href=\'https://img.client.10010.com/dwguide/index.html?title=%E6%AD%A3%E5%9C%A8%E6%9F%A5%E8%AF%A2&sharerMobile=&openUrl=https%3A%2F%2Fm.client.10010.com%2Fmobileservicequery%2FoperationserviceNew%2FqueryOrderRelationship\'\"><img src=\"img/20161026175344.png\" onerror=\"javascript:this.src=\'https://img.client.10010.com/mobileService/view/client/wap/images/default_logo.png\';\" class=\"tu1\">");
document.writeln("                <p>隐藏业务(1)</p>");
document.writeln("            </li>");
document.writeln("            <li name=\"\" onclick=\"window.location.href=\'https://img.client.10010.com/dwguide/index.html?title=%E6%AD%A3%E5%9C%A8%E6%9F%A5%E8%AF%A2&sharerMobile=&openUrl=https%3A%2F%2Fm.client.10010.com%2Fmobileservicequery%2Fquery%2FqueryBusinessRecordDetails\'\"><img src=\"img/20161026175413.png\" onerror=\"javascript:this.src=\'https://img.client.10010.com/mobileService/view/client/wap/images/default_logo.png\';\" class=\"tu1\">");
document.writeln("                <p>隐藏业务(2)</p>");
document.writeln("            </li>");
document.writeln("        </ul>");
document.writeln("    </div>");
document.writeln("</div>");
document.writeln("<div class=\"t2 div_nav\">");
document.writeln("    <div class=\"t1_2\">");
document.writeln("        <ul>");
document.writeln("            <!--<li name=\"\"onclick=\"window.location.href=\'\'\">-->");
document.writeln("            <li name=\"\" onclick=\"window.location.href=\'https://wap.10010.com/mobileService/operationservice/queryOrderRelationshipTwo.htm\'\"><img src=\"img/20161026170548.png\" onerror=\"javascript:this.src=\'https://img.client.10010.com/mobileService/view/client/wap/images/default_logo.png\';\" class=\"tu1\">");
document.writeln("                <p>我已订购</p>");
document.writeln("            </li>");
document.writeln("            <li name=\"\" onclick=\"window.location.href=\'https://wap.10010.com/mobileService/operationservice/queryWoComboSpare.htm\'\"><img src=\"img/20161026170637.png\" onerror=\"javascript:this.src=\'https://img.client.10010.com/mobileService/view/client/wap/images/default_logo.png\';\" class=\"tu1\">");
document.writeln("                <p>余量查询</p>");
document.writeln("            </li>");
document.writeln("            <li name=\"\" onclick=\"window.location.href=\'https://wap.10010.com/mobileService/operationservice/queryHistoryBusinessBL.htm\'\"><img src=\"img/20161026171543.png\" onerror=\"javascript:this.src=\'https://img.client.10010.com/mobileService/view/client/wap/images/default_logo.png\';\" class=\"tu1\">");
document.writeln("                <p>业务办理记录</p>");
document.writeln("            </li>");
document.writeln("            <li name=\"\" onclick=\"window.location.href=\'http://wap.10010.com/mobileService/operationservice/get_my_package.htm\'\"><img src=\"img/b9c2a15c7dd1f37c.png\" onerror=\"javascript:this.src=\'https://img.client.10010.com/mobileService/view/client/wap/images/default_logo.png\';\" class=\"tu1\">");
document.writeln("                <p>我的套餐</p>");
document.writeln("            </li>");
document.writeln("            <li name=\"\" onclick=\"window.location.href=\'http://wap.10010.com/mobileService/common/skip/queryRealTimeFee.htm?navUrlCode=1160&activiChannel=wap\'\"><img src=\"img/20161026172853.png\" onerror=\"javascript:this.src=\'https://img.client.10010.com/mobileService/view/client/wap/images/default_logo.png\';\" class=\"tu1\">");
document.writeln("                <p>实时话费</p>");
document.writeln("            </li>");
document.writeln("            <li name=\"\" onclick=\"window.location.href=\'http://wap.10010.com/mobileService/common/skip/queryBalance.htm?navUrlCode=1144&activiChannel=wap\'\"><img src=\"img/20161026173300.png\" onerror=\"javascript:this.src=\'https://img.client.10010.com/mobileService/view/client/wap/images/default_logo.png\';\" class=\"tu1\">");
document.writeln("                <p>账户余额</p>");
document.writeln("            </li>");
document.writeln("            <li name=\"\" onclick=\"window.location.href=\'http://upay.10010.com/npfwap/npfMobWap/query/index.html?navUrlCode=1217&activiChannel=wap\'\"><img src=\"img/20200807103824.png\" onerror=\"javascript:this.src=\'https://img.client.10010.com/mobileService/view/client/wap/images/default_logo.png\';\" class=\"tu1\">");
document.writeln("                <p>交费记录</p>");
document.writeln("            </li>");
document.writeln("        </ul>");
document.writeln("    </div>");
document.writeln("</div>");
document.writeln("<div class=\"t3 div_nav\">");
document.writeln("    <div class=\"t1_3\">");
document.writeln("        <ul>");
document.writeln("            <li name=\"\" onclick=\"window.location.href=\'http://u.10010.cn/qAAei\'\"><img src=\"img/20170224145740.png\" onerror=\"javascript:this.src=\'https://img.client.10010.com/mobileService/view/client/wap/images/default_logo.png\';\" class=\"tu1\">");
document.writeln("                <p>交费充值</p>");
document.writeln("            </li>");
document.writeln("            <li name=\"\" onclick=\"window.location.href=\'http://wap.10010.com/mobileService/view/client/fill/newFixCharge.jsp?navUrlCode=1090\'\"><img src=\"img/20170224145808.png\" onerror=\"javascript:this.src=\'https://img.client.10010.com/mobileService/view/client/wap/images/default_logo.png\';\" class=\"tu1\">");
document.writeln("                <p>充值卡充值</p>");
document.writeln("            </li>");
document.writeln("            <li name=\"\" onclick=\"window.location.href=\'https://upay.10010.com/npfwap/npfMobWap/closeAccount/index.html?navUrlCode=1323\'\"><img src=\"img/20190827172359.png\" onerror=\"javascript:this.src=\'https://img.client.10010.com/mobileService/view/client/wap/images/default_logo.png\';\" class=\"tu1\">");
document.writeln("                <p>销户号码交费</p>");
document.writeln("            </li>");
document.writeln("            <li name=\"\" onclick=\"window.location.href=\'https://img.client.10010.com/jifenshangcheng/goodsdetail?goodsId=8a29ac8a75a30e4e0175ba89c3dc1009\'\"><img src=\"img/20161026171253.png\" onerror=\"javascript:this.src=\'https://img.client.10010.com/mobileService/view/client/wap/images/default_logo.png\';\" class=\"tu1\">");
document.writeln("                <p>积分兑换(5元)</p>");
document.writeln("            </li>");
document.writeln("            <li name=\"\" onclick=\"window.location.href=\'https://img.client.10010.com/jifenshangcheng/goodsdetail?goodsId=8a29ac8a75a30e4e0175b721ae490a5a\'\"><img src=\"img/20161026171253.png\" onerror=\"javascript:this.src=\'https://img.client.10010.com/mobileService/view/client/wap/images/default_logo.png\';\" class=\"tu1\">");
document.writeln("                <p>积分兑换(10元)</p>");
document.writeln("            </li>");
document.writeln("            <li name=\"\" onclick=\"window.location.href=\'https://img.client.10010.com/jifenshangcheng/goodsdetail?goodsId=8a29ac8a7aa5a75d017aa81f68c40131\'\"><img src=\"img/20161026171253.png\" onerror=\"javascript:this.src=\'https://img.client.10010.com/mobileService/view/client/wap/images/default_logo.png\';\" class=\"tu1\">");
document.writeln("                <p>积分兑换(20元)</p>");
document.writeln("            </li>");
document.writeln("            <li name=\"\" onclick=\"window.location.href=\'https://img.client.10010.com/jifenshangcheng/goodsdetail?goodsId=8a29ac8a7aa5a75d017aa8254e900154\'\"><img src=\"img/20161026171253.png\" onerror=\"javascript:this.src=\'https://img.client.10010.com/mobileService/view/client/wap/images/default_logo.png\';\" class=\"tu1\">");
document.writeln("                <p>积分兑换(50元)</p>");
document.writeln("            </li>");
document.writeln("            <li name=\"\" onclick=\"window.location.href=\'https://img.client.10010.com/jifenshangcheng/goodsdetail?goodsId=8a29ac897aa5a75c017aa829c5ef0310\'\"><img src=\"img/20161026171253.png\" onerror=\"javascript:this.src=\'https://img.client.10010.com/mobileService/view/client/wap/images/default_logo.png\';\" class=\"tu1\">");
document.writeln("                <p>积分兑换(100元)</p>");
document.writeln("            </li>");
document.writeln("            <li name=\"\" onclick=\"window.location.href=\'https://img.client.10010.com/jifenshangcheng/goodsdetail?goodsId=8a29ac897aa5a75c017aa827587202ed\'\"><img src=\"img/20161026171253.png\" onerror=\"javascript:this.src=\'https://img.client.10010.com/mobileService/view/client/wap/images/default_logo.png\';\" class=\"tu1\">");
document.writeln("                <p>积分兑换(200元)</p>");
document.writeln("            </li>");
document.writeln("            <li name=\"\" onclick=\"window.location.href=\'https://m.tb.cn/h.UONK4po\'\"><img src=\"img/20190827172359.png\" onerror=\"javascript:this.src=\'https://img.client.10010.com/mobileService/view/client/wap/images/default_logo.png\';\" class=\"tu1\">");
document.writeln("                <p>领话费1</br>月底截止</p>");
document.writeln("            </li>");
document.writeln("            <li name=\"\" onclick=\"window.location.href=\'https://3.cn/1-C21UPJ\'\"><img src=\"img/20161026172853.png\" onerror=\"javascript:this.src=\'https://img.client.10010.com/mobileService/view/client/wap/images/default_logo.png\';\" class=\"tu1\">");
document.writeln("                <p>京东</br>积分兑换/快充</p>");
document.writeln("            </li>");
document.writeln("            <li name=\"\" onclick=\"window.location.href=\'https://atp.bol.wo.cn/atp/unity/ACT20230131100038497641339qF2T?product=woemail\'\"><img src=\"img/20190827172359.png\" onerror=\"javascript:this.src=\'https://img.client.10010.com/mobileService/view/client/wap/images/default_logo.png\';\" class=\"tu1\">");
document.writeln("                <p>每月领1元话费</br>月底截止</p>");
document.writeln("            </li>");
document.writeln("            <li name=\"\" onclick=\"window.location.href=\'https://u.jd.com/FMPjwJs\'\"><img src=\"img/20161026173300.png\" onerror=\"javascript:this.src=\'https://img.client.10010.com/mobileService/view/client/wap/images/default_logo.png\';\" class=\"tu1\">");
document.writeln("                <p>慢充·50话费</br>限时9折起</p>");
document.writeln("            </li>");
document.writeln("            <li name=\"\" onclick=\"window.location.href=\'https://u.jd.com/FCD1UaK\'\"><img src=\"img/20161026173300.png\" onerror=\"javascript:this.src=\'https://img.client.10010.com/mobileService/view/client/wap/images/default_logo.png\';\" class=\"tu1\">");
document.writeln("                <p>慢充·100话费</br>限时9折起</p>");
document.writeln("            </li>");
document.writeln("            <li name=\"\" onclick=\"window.location.href=\'https://u.jd.com/FMPffXS\'\"><img src=\"img/20161026173300.png\" onerror=\"javascript:this.src=\'https://img.client.10010.com/mobileService/view/client/wap/images/default_logo.png\';\" class=\"tu1\">");
document.writeln("                <p>慢充·200话费</br>限时9折起</p>");
document.writeln("            </li>");
document.writeln("            <li name=\"\" onclick=\"window.location.href=\'https://pay262.github.io/tx/img/abc_gd.jpg\'\"><img src=\"img/20190827172359.png\" onerror=\"javascript:this.src=\'https://img.client.10010.com/mobileService/view/client/wap/images/default_logo.png\';\" class=\"tu1\">");
document.writeln("                <p>广东农行30-5</br>3月31日截止</p>");
document.writeln("            </li>");
document.writeln("        </ul>");
document.writeln("    </div>");
document.writeln("</div>");
document.writeln("<div class=\"t4 div_nav\">");
document.writeln("    <div class=\"t1_4\">");
document.writeln("        <ul>");
document.writeln("            <li name=\"\" onclick=\"window.location.href=\'https://getsimnum.caict.ac.cn/m/#/\'\"><img src=\"img/20161026171253.png\" onerror=\"javascript:this.src=\'https://img.client.10010.com/mobileService/view/client/wap/images/default_logo.png\';\" class=\"tu1\">");
document.writeln("                <p>一证通查</p>");
document.writeln("            </li>");
document.writeln("            <li name=\"\" onclick=\"window.location.href=\'https://img.client.10010.com/dwguide/index.html?title=%E6%88%91%E7%9A%84%E7%A4%BC%E5%8C%85&duanlianjieabc=&actCode=&sharerMobile=&openUrl=https%3A%2F%2Fm.client.10010.com%2FmyPrizeForActivity%2Fquerywinninglist.htm\'\"><img src=\"img/20161026173300.png\" onerror=\"javascript:this.src=\'https://img.client.10010.com/mobileService/view/client/wap/images/default_logo.png\';\" class=\"tu1\">");
document.writeln("                <p>我的礼包</p>");
document.writeln("            </li>");
document.writeln("            <li name=\"\" onclick=\"window.location.href=\'https://txwk.10010.com/t/8hzk8\'\"><img src=\"img/20161026174033.png\" onerror=\"javascript:this.src=\'https://img.client.10010.com/mobileService/view/client/wap/images/default_logo.png\';\" class=\"tu1\">");
document.writeln("                <p>王卡宽带预约</p>");
document.writeln("            </li>");
document.writeln("            <li name=\"\" onclick=\"window.location.href=\'https://img.client.10010.com/5gshengjibaoduannei/index.html?channel=5Gzhuanqu-fuwu#/home\'\"><img src=\"img/cb28db500e1f8cfa-1.png\" onerror=\"javascript:this.src=\'https://img.client.10010.com/mobileService/view/client/wap/images/default_logo.png\';\" class=\"tu1\">");
document.writeln("                <p>5G升级月包</p>");
document.writeln("            </li>");
document.writeln("            <li name=\"\" onclick=\"window.location.href=\'http://speed.unicomgd.com:8080/\'\"><img src=\"img/20161026170637.png\" onerror=\"javascript:this.src=\'https://img.client.10010.com/mobileService/view/client/wap/images/default_logo.png\';\" class=\"tu1\">");
document.writeln("                <p>宽带测速</p>");
document.writeln("            </li>");
document.writeln("            <li name=\"\" onclick=\"window.location.href=\'https://m.tb.cn/h.URjjrIh?tk=oQaqddlSkOv\'\">");
document.writeln("                <!--<img src=\"img/cb28db500e1f8cfa-1.png\"onerror=\"javascript:this.src=\'https://img.client.10010.com/mobileService/view/client/wap/images/default_logo.png\';\"class=\"tu1\"><p>5G升级日包</p></li><li name=\"\"onclick=\"window.location.href=\'https://m.client.10010.com/mobileService/businessTransact/iceNoLimitsFlow/iceNolimitsFlowDetail.htm\'\"><img src=\"img/20161026172853.png\"onerror=\"javascript:this.src=\'https://img.client.10010.com/mobileService/view/client/wap/images/default_logo.png\';\"class=\"tu1\"><p>畅享用流量包</p></li><li name=\"\"onclick=\"window.location.href=\'https://img.client.10010.com/yuyintehuibao/index.html\'\"><img src=\"img/20161026173300.png\"onerror=\"javascript:this.src=\'https://img.client.10010.com/mobileService/view/client/wap/images/default_logo.png\';\"class=\"tu1\"><p>语音特惠包</p></li><li name=\"\"onclick=\"window.location.href=\'https://txwk.10010.com/KCard/wxCommon/goto_direct?state=KCARD_CASH_INVITE_ORDER&IdType=union_id&ShareID=McpNSj29zvTpY3rcZRYy3zzdHIL5kalYvruUXKf3YzU&channel=01-0379-a5ar-a6xw&ADTAG=01-0379-a5ar-a6xw\'\"><img src=\"img/20200807103824.png\"onerror=\"javascript:this.src=\'https://img.client.10010.com/mobileService/view/client/wap/images/default_logo.png\';\"class=\"tu1\"><p>超值套餐</br></p></li><li name=\"\"onclick=\"window.location.href=\'https://spyyt.10010.com/rcb?scene=06&chnl=04\'\"><img src=\"img/20161026175413.png\"onerror=\"javascript:this.src=\'https://img.client.10010.com/mobileService/view/client/wap/images/default_logo.png\';\"class=\"tu1\"><p>视频营业厅</p></li><li name=\"\"onclick=\"window.location.href=\'http://u.10010.cn/qA7K3\'\"><img src=\"img/20161026175256.png\"onerror=\"javascript:this.src=\'https://img.client.10010.com/mobileService/view/client/wap/images/default_logo.png\';\"class=\"tu1\"><p>套餐升级福利</p></li><li name=\"\"onclick=\"window.location.href=\'https://huodong.10155.com/h5/hdact3/spcl-ahWojoy.html#/index?channel=3000007549\'\"><img src=\"img/20161026175413.png\"onerror=\"javascript:this.src=\'https://img.client.10010.com/mobileService/view/client/wap/images/default_logo.png\';\"class=\"tu1\"><p>沃享视频会员</p></li><li name=\"\"onclick=\"window.location.href=\'https://guanjia.10010.com/product?sgChannel=3&product=2\'\"><img src=\"img/20161026175532.png\"onerror=\"javascript:this.src=\'https://img.client.10010.com/mobileService/view/client/wap/images/default_logo.png\';\"class=\"tu1\"><p>手机管家</br></p></li><li name=\"\"onclick=\"window.location.href=\'https://img.client.10010.com/2023springfestival/#/Login?shareCode=&channel=UnicomAppN11\'\"><img src=\"img/20161026175256.png\"onerror=\"javascript:this.src=\'https://img.client.10010.com/mobileService/view/client/wap/images/default_logo.png\';\"class=\"tu1\"><p>2022年度报告</p></li><li name=\"\"onclick=\"window.location.href=\'https://qy.chinaunicom.cn/mobile-h5/2023/draw.html\'\"><img src=\"img/20161026173300.png\"onerror=\"javascript:this.src=\'https://img.client.10010.com/mobileService/view/client/wap/images/default_logo.png\';\"class=\"tu1\"><p>免费抽好礼</br></p></li><li name=\"\"onclick=\"window.location.href=\'https://club.10010.com/uf/daily/draw?isAuto=true&shorturl=8b40e5\'\"><img src=\"img/20161026173300.png\"onerror=\"javascript:this.src=\'https://img.client.10010.com/mobileService/view/client/wap/images/default_logo.png\';\"class=\"tu1\"><p>每日抽E卡</br></p></li><li name=\"\"onclick=\"window.location.href=\'https://qy.chinaunicom.cn/u/d5d126408a314272953d5a875fa8b679\'\"><img src=\"img/20161026173300.png\"onerror=\"javascript:this.src=\'https://img.client.10010.com/mobileService/view/client/wap/images/default_logo.png\';\"class=\"tu1\"><p>开盲盒抽会员</br></p></li><li name=\"\"onclick=\"window.location.href=\'https://qy.chinaunicom.cn/u/db7f686bc93943eb9597e74943394605\'\"><img src=\"img/20161026173300.png\"onerror=\"javascript:this.src=\'https://img.client.10010.com/mobileService/view/client/wap/images/default_logo.png\';\"class=\"tu1\"><p>开会员抽好礼</br></p></li></ul></div></div><div class=\"t5 div_nav\"><div class=\"t1_5\"><ul><li name=\"\"onclick=\"window.location.href=\'https://sourl.cn/U88mdD\'\"><img src=\"img/20161026175846.png\"onerror=\"javascript:this.src=\'https://img.client.10010.com/mobileService/view/client/wap/images/default_logo.png\';\"class=\"tu1\"><p>广东·专区</br>移步到羊毛汇</p></li><li name=\"\"onclick=\"window.location.href=\'https://wsm.wx.yn10010.com/hall/millionWelfare\'\"><img src=\"img/20161026175846.png\"onerror=\"javascript:this.src=\'https://img.client.10010.com/mobileService/view/client/wap/images/default_logo.png\';\"class=\"tu1\"><p>云南·抽百万福利</p></li><li name=\"\"onclick=\"window.location.href=\'http://bjwys.bjunicom.com.cn/apps/shareapps/pub-page/updatePackage/customInfoNew.html?shopId=01153114&qrcodeId=0130914179&goodsTypeCode=2019122500012429&y7bRbP=qAkSqarjFbNjFbNjFXsay2hNZLP8BR3Ngn5uxkfnu4ZqqEQEbG_lqAqqFG\'\"><img src=\"img/20161026175846.png\"onerror=\"javascript:this.src=\'https://img.client.10010.com/mobileService/view/client/wap/images/default_logo.png\';\"class=\"tu1\"><p>北京·5g升级包</p></li><li name=\"\"onclick=\"window.location.href=\'https://wechat.zj186.com/wechat-route-rest-1.0/view/emallCustomer/index?developId=15657475102\'\"><img src=\"img/20161026175846.png\"onerror=\"javascript:this.src=\'https://img.client.10010.com/mobileService/view/client/wap/images/default_logo.png\';\"class=\"tu1\"><p>浙江·每月抽奖</p></li><li name=\"\"onclick=\"window.location.href=\'https://wsm.wx.yn10010.com/sms2/lyh\'\"><img src=\"img/20161026175846.png\"onerror=\"javascript:this.src=\'https://img.client.10010.com/mobileService/view/client/wap/images/default_logo.png\';\"class=\"tu1\"><p>云南·充值送</p></li><li name=\"\"onclick=\"window.location.href=\'https://ahlyh.ahlt10010.com/app/oldUserWx/index?number=\'\"><img src=\"img/20161026175846.png\"onerror=\"javascript:this.src=\'https://img.client.10010.com/mobileService/view/client/wap/images/default_logo.png\';\"class=\"tu1\"><p>安徽·老用户专区</p></li><li name=\"\"onclick=\"window.location.href=\'https://u.10010.cn/qAtZB\'\"><img src=\"img/20161026175846.png\"onerror=\"javascript:this.src=\'https://img.client.10010.com/mobileService/view/client/wap/images/default_logo.png\';\"class=\"tu1\"><p>湖南·精彩活动</p></li><li name=\"\"onclick=\"window.location.href=\'http://u.10010.cn/0tyKaxuN\'\"><img src=\"img/20161026175846.png\"onerror=\"javascript:this.src=\'https://img.client.10010.com/mobileService/view/client/wap/images/default_logo.png\';\"class=\"tu1\"><p>湖北·抽奖活动</br></p></li><li name=\"\"onclick=\"window.location.href=\'https://wx.hnliantong.com/h5/cl/index.html?source=2&channel_id=&openid=oZSTft3pv91FBq-eODNKRjD3FVLc&isBindMobile=0#/product/71\'\"><img src=\"img/20161026175846.png\"onerror=\"javascript:this.src=\'https://img.client.10010.com/mobileService/view/client/wap/images/default_logo.png\';\"class=\"tu1\"><p>湖南·5g加油包</br></p></li><li name=\"\"onclick=\"window.location.href=\'https://m.10010.com/scaffold-show/push/74Nsm4M1Kjd?channel=06-2279-af44-aj7q&duanlianjieabc=jykdwxtw\'\"><img src=\"img/20161026175846.png\"onerror=\"javascript:this.src=\'https://img.client.10010.com/mobileService/view/client/wap/images/default_logo.png\';\"class=\"tu1\"><p>湖南·千兆宽带</br></p></li><li name=\"\"onclick=\"window.location.href=\'https://m.client.10010.com/error/busy.html\'\"><img src=\"img/20161026175846.png\"onerror=\"javascript:this.src=\'https://img.client.10010.com/mobileService/view/client/wap/images/default_logo.png\';\"class=\"tu1\"><p>河南·200M</br>低消宽带</p></li><li name=\"\"onclick=\"window.location.href=\'https://yxmapp.169ol.com/wact/webfontsbackup/index.html?#/index\'\"><img src=\"img/20161026175846.png\"onerror=\"javascript:this.src=\'https://img.client.10010.com/mobileService/view/client/wap/images/default_logo.png\';\"class=\"tu1\"><p>四川·养熊猫</br>电子券京东卡</p></li><!--<li name=\"\"onclick=\"window.location.href=\'https://m.client.10010.com/error/busy1.htm\'\"><img src=\"img/20161026175846.png\"onerror=\"javascript:this.src=\'https://img.client.10010.com/mobileService/view/client/wap/images/default_logo.png\';\"class=\"tu1\"><p>陕西</br>900分钟＋150g</p></li>-->");
document.writeln("            <li name=\"\" onclick=\"window.location.href=\'https://m.10010.com/scaffold-show/subject/18ETxw8zGxZ?duanlianjieabc=qAv9i\'\"><img src=\"img/20161026175846.png\" onerror=\"javascript:this.src=\'https://img.client.10010.com/mobileService/view/client/wap/images/default_logo.png\';\" class=\"tu1\">");
document.writeln("                <p>河北·福利月月领</br></p>");
document.writeln("            </li>");
document.writeln("            <li name=\"\" onclick=\"window.location.href=\'https://wxst.xsyyzx.top:8092/flowGather/#/\'\"><img src=\"img/20161026175846.png\" onerror=\"javascript:this.src=\'https://img.client.10010.com/mobileService/view/client/wap/images/default_logo.png\';\" class=\"tu1\">");
document.writeln("                <p>陕西·流量集合</br></p>");
document.writeln("            </li>");
document.writeln("            <li name=\"\" onclick=\"window.location.href=\'https://u.10010.cn/qAVsg\'\"><img src=\"img/20161026175846.png\" onerror=\"javascript:this.src=\'https://img.client.10010.com/mobileService/view/client/wap/images/default_logo.png\';\" class=\"tu1\">");
document.writeln("                <p>江西·5g优享包</br></p>");
document.writeln("            </li>");
document.writeln("        </ul>");
document.writeln("    </div>");
document.writeln("</div>");
document.writeln("<div class=\"t5 div_nav\">");
document.writeln("    <div class=\"t1_5\">");
document.writeln("        <ul>");
document.writeln("            <!--<div class=\"top1\"><a href=\"#\"><img width=\"290rem\"height=\"100rem\"src=\"img/bg01.jpg\"></a></div>-->");
document.writeln("            <li name=\"\" onclick=\"window.location.href=\'https://sourl.cn/U88mdD\'\"><img src=\"img/20161026175846.png\" onerror=\"javascript:this.src=\'https://img.client.10010.com/mobileService/view/client/wap/images/default_logo.png\';\" class=\"tu1\">");
document.writeln("                <p>广东·专区</br>移步到羊毛汇</p>");
document.writeln("            </li>");
document.writeln("            <li name=\"\" onclick=\"window.location.href=\'https://wsm.wx.yn10010.com/hall/millionWelfare\'\"><img src=\"img/20161026175846.png\" onerror=\"javascript:this.src=\'https://img.client.10010.com/mobileService/view/client/wap/images/default_logo.png\';\" class=\"tu1\">");
document.writeln("                <p>云南·抽百万福利</p>");
document.writeln("            </li>");
document.writeln("            <li name=\"\" onclick=\"window.location.href=\'http://bjwys.bjunicom.com.cn/apps/shareapps/pub-page/updatePackage/customInfoNew.html?shopId=01153114&qrcodeId=0130914179&goodsTypeCode=2019122500012429&y7bRbP=qAkSqarjFbNjFbNjFXsay2hNZLP8BR3Ngn5uxkfnu4ZqqEQEbG_lqAqqFG\'\"><img src=\"img/20161026175846.png\" onerror=\"javascript:this.src=\'https://img.client.10010.com/mobileService/view/client/wap/images/default_logo.png\';\" class=\"tu1\">");
document.writeln("                <p>北京·5g升级包</p>");
document.writeln("            </li>");
document.writeln("            <li name=\"\" onclick=\"window.location.href=\'https://wechat.zj186.com/wechat-route-rest-1.0/view/emallCustomer/index?developId=15657475102\'\"><img src=\"img/20161026175846.png\" onerror=\"javascript:this.src=\'https://img.client.10010.com/mobileService/view/client/wap/images/default_logo.png\';\" class=\"tu1\">");
document.writeln("                <p>浙江·每月抽奖</p>");
document.writeln("            </li>");
document.writeln("            <li name=\"\" onclick=\"window.location.href=\'https://wsm.wx.yn10010.com/sms2/lyh\'\"><img src=\"img/20161026175846.png\" onerror=\"javascript:this.src=\'https://img.client.10010.com/mobileService/view/client/wap/images/default_logo.png\';\" class=\"tu1\">");
document.writeln("                <p>云南·充值送</p>");
document.writeln("            </li>");
document.writeln("            <li name=\"\" onclick=\"window.location.href=\'https://ahlyh.ahlt10010.com/app/oldUserWx/index?number=\'\"><img src=\"img/20161026175846.png\" onerror=\"javascript:this.src=\'https://img.client.10010.com/mobileService/view/client/wap/images/default_logo.png\';\" class=\"tu1\">");
document.writeln("                <p>安徽·老用户专区</p>");
document.writeln("            </li>");
document.writeln("            <li name=\"\" onclick=\"window.location.href=\'https://u.10010.cn/qAtZB\'\"><img src=\"img/20161026175846.png\" onerror=\"javascript:this.src=\'https://img.client.10010.com/mobileService/view/client/wap/images/default_logo.png\';\" class=\"tu1\">");
document.writeln("                <p>湖南·精彩活动</p>");
document.writeln("            </li>");
document.writeln("            <li name=\"\" onclick=\"window.location.href=\'http://u.10010.cn/0tyKaxuN\'\"><img src=\"img/20161026175846.png\" onerror=\"javascript:this.src=\'https://img.client.10010.com/mobileService/view/client/wap/images/default_logo.png\';\" class=\"tu1\">");
document.writeln("                <p>湖北·抽奖活动</br></p>");
document.writeln("            </li>");
document.writeln("            <li name=\"\" onclick=\"window.location.href=\'https://wx.hnliantong.com/h5/cl/index.html?source=2&channel_id=&openid=oZSTft3pv91FBq-eODNKRjD3FVLc&isBindMobile=0#/product/71\'\"><img src=\"img/20161026175846.png\" onerror=\"javascript:this.src=\'https://img.client.10010.com/mobileService/view/client/wap/images/default_logo.png\';\" class=\"tu1\">");
document.writeln("                <p>湖南·5g加油包</br></p>");
document.writeln("            </li>");
document.writeln("            <!--<li name=\"\"onclick=\"window.location.href=\'https://82612.activity-17.m.duiba.com.cn/projectx/pfa8c49f1/f6a81faf1.html?appKey=3g9BRP5HuZCGg9Hk3tudXpGEF7hE&openBs=openbs&shareCode=C378W6\'\"><img src=\"img/20161026175846.png\"onerror=\"javascript:this.src=\'https://img.client.10010.com/mobileService/view/client/wap/images/default_logo.png\';\"class=\"tu1\"><p>湖南·话费券</p></li>-->");
document.writeln("            <li name=\"\" onclick=\"window.location.href=\'https://m.10010.com/scaffold-show/push/74Nsm4M1Kjd?channel=06-2279-af44-aj7q&duanlianjieabc=jykdwxtw\'\"><img src=\"img/20161026175846.png\" onerror=\"javascript:this.src=\'https://img.client.10010.com/mobileService/view/client/wap/images/default_logo.png\';\" class=\"tu1\">");
document.writeln("                <p>湖南·千兆宽带</br></p>");
document.writeln("            </li>");
document.writeln("            <!--<li name=\"\"onclick=\"window.location.href=\'https://u.10010.cn/0tyJHGVN\'\"><img src=\"img/20161026175846.png\"onerror=\"javascript:this.src=\'https://img.client.10010.com/mobileService/view/client/wap/images/default_logo.png\';\"class=\"tu1\"><p>长沙·话费红包</p></li><li name=\"\"onclick=\"window.location.href=\'http://u.10010.cn/0tyJ7PrO\'\"><img src=\"img/20161026175846.png\"onerror=\"javascript:this.src=\'https://img.client.10010.com/mobileService/view/client/wap/images/default_logo.png\';\"class=\"tu1\"><p>福州·话费红包</p></li>-->");
document.writeln("            <!--<li name=\"\"onclick=\"window.location.href=\'https://om.51186.com.cn/woscancode/sdDoubleCloud/toFamilyVPN?key=UPaLLod7R/yHMUaSQoYTmzMSzcs%2BsJDpYYwxNQMRFpmwsLaHpJAZ7JwdSJHStdDJBWLTO3Ki/Zc=\'\"><img src=\"img/20161026175846.png\"onerror=\"javascript:this.src=\'https://img.client.10010.com/mobileService/view/client/wap/images/default_logo.png\';\"class=\"tu1\"><p>山东·亲情网</br></p></li>-->");
document.writeln("            <li name=\"\" onclick=\"window.location.href=\'https://m.client.10010.com/error/busy.html\'\"><img src=\"img/20161026175846.png\" onerror=\"javascript:this.src=\'https://img.client.10010.com/mobileService/view/client/wap/images/default_logo.png\';\" class=\"tu1\">");
document.writeln("                <p>河南·200M</br>低消宽带</p>");
document.writeln("            </li>");
document.writeln("            <li name=\"\" onclick=\"window.location.href=\'https://yxmapp.169ol.com/wact/webfontsbackup/index.html?#/index\'\"><img src=\"img/20161026175846.png\" onerror=\"javascript:this.src=\'https://img.client.10010.com/mobileService/view/client/wap/images/default_logo.png\';\" class=\"tu1\">");
document.writeln("                <p>四川·养熊猫</br>电子券京东卡</p>");
document.writeln("            </li>");
document.writeln("            <!--<li name=\"\"onclick=\"window.location.href=\'https://m.client.10010.com/error/busy1.htm\'\"><img src=\"img/20161026175846.png\"onerror=\"javascript:this.src=\'https://img.client.10010.com/mobileService/view/client/wap/images/default_logo.png\';\"class=\"tu1\"><p>陕西</br>900分钟＋150g</p></li>-->");
document.writeln("            <li name=\"\" onclick=\"window.location.href=\'https://m.10010.com/scaffold-show/subject/18ETxw8zGxZ?duanlianjieabc=qAv9i\'\"><img src=\"img/20161026175846.png\" onerror=\"javascript:this.src=\'https://img.client.10010.com/mobileService/view/client/wap/images/default_logo.png\';\" class=\"tu1\">");
document.writeln("                <p>河北·福利月月领</br></p>");
document.writeln("            </li>");
document.writeln("            <li name=\"\" onclick=\"window.location.href=\'https://wxst.xsyyzx.top:8092/flowGather/#/\'\"><img src=\"img/20161026175846.png\" onerror=\"javascript:this.src=\'https://img.client.10010.com/mobileService/view/client/wap/images/default_logo.png\';\" class=\"tu1\">");
document.writeln("                <p>陕西·流量集合</br></p>");
document.writeln("            </li>");
document.writeln("            <li name=\"\" onclick=\"window.location.href=\'https://u.10010.cn/qAVsg\'\"><img src=\"img/20161026175846.png\" onerror=\"javascript:this.src=\'https://img.client.10010.com/mobileService/view/client/wap/images/default_logo.png\';\" class=\"tu1\">");
document.writeln("                <p>江西·5g优享包</br></p>");
document.writeln("            </li>");
document.writeln("        </ul>");
document.writeln("    </div>");
document.writeln("</div>");
document.writeln("<div class=\"t6 div_nav\">");
document.writeln("    <div class=\"t1_6\">");
document.writeln("        <ul>");
document.writeln("            <li name=\"\" onclick=\"window.location.href=\'http://u.10010.cn/0tylhMUT\'\"><img src=\"img/20161026175846.png\" onerror=\"javascript:this.src=\'https://img.client.10010.com/mobileService/view/client/wap/images/default_logo.png\';\" class=\"tu1\">");
document.writeln("                <p>天天秒杀</br>签到</p>");
document.writeln("            </li>");
document.writeln("            <li name=\"\" onclick=\"window.location.href=\'https://wx.hnliantong.com/h5/cl/index.html?source=1#/product/125\'\"><img src=\"img/20161026175846.png\" onerror=\"javascript:this.src=\'https://img.client.10010.com/mobileService/view/client/wap/images/default_logo.png\';\" class=\"tu1\">");
document.writeln("                <p>100元40G</br>5年共享版</p>");
document.writeln("            </li>");
document.writeln("        </ul>");
document.writeln("    </div>");
document.writeln("</div>");
document.writeln("");
